name: darth_agent_example
description: An example project demonstrating how to use Darth_Agent.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  darth_agent:
    path: ../ 
  
  # LangChain dependencies
  langchain: ^0.4.1
  langchain_chroma: ^0.1.0+15
